const patterns = [
  ['Singleton','Creational','Shares one session context across the application.'],['Factory Method','Creational','Creates role-specific healthcare users through a common factory.'],['Abstract Factory','Creational','Builds compatible clinic or hospital service families.'],['Builder','Creational','Assembles complete medical records from validated fields.'],['Prototype','Creational','Copies reusable consultation record templates.'],
  ['Adapter','Structural','Connects an external payment gateway to HealthSync payments.'],['Bridge','Structural','Separates healthcare services from their delivery channel.'],['Composite','Structural','Organizes departments and services into a care hierarchy.'],['Decorator','Structural','Adds optional services and charges to an appointment.'],['Facade','Structural','Coordinates common multi-service healthcare workflows.'],['Flyweight','Structural','Reuses shared medicine, test, and specialty reference data.'],['Proxy','Structural','Checks authorization before medical record access.'],
  ['Chain of Responsibility','Behavioral','Routes an emergency request through triage handlers.'],['Command','Behavioral','Packages appointment actions as executable commands.'],['Interpreter','Behavioral','Evaluates simple healthcare report query expressions.'],['Iterator','Behavioral','Traverses combined patient appointment and record history.'],['Mediator','Behavioral','Routes messages between care team participants.'],['Memento','Behavioral','Saves and restores medical record draft snapshots.'],['Observer','Behavioral','Notifies subscribers when healthcare domain events occur.'],['State','Behavioral','Controls valid appointment lifecycle transitions.'],['Strategy','Behavioral','Selects appointment priority or payment behavior.'],['Template Method','Behavioral','Defines shared steps for generating healthcare reports.'],['Visitor','Behavioral','Applies reporting operations to medical record elements.']
];
const descriptions = {
  dashboard:'Dashboard',appointments:'Appointments',records:'Medical Records',prescriptions:'Prescriptions',payments:'Payments',notifications:'Notifications',emergency:'Emergency Assistance',reports:'Reports',patterns:'Design Patterns'
};
const content=document.querySelector('#content');
const modal=document.querySelector('#modal');
function header(title,sub='A clear view of your care, all in one place.'){return `<div class="welcome"><div><h1>${title}</h1><p>${sub}</p></div><span class="demo-pill">DEMO DATA · NOT REAL PATIENT INFORMATION</span></div>`}
function badge(text,kind='green'){return `<span class="badge ${kind}">${text}</span>`}
function panelHead(title,action=''){return `<div class="panel-head"><h2>${title}</h2>${action}</div>`}
function appointmentRow(day,month,title,doctor,time,status,kind){return `<div class="appointment-row"><div class="date-block"><strong>${day}</strong><small>${month}</small></div><div class="appointment-info"><strong>${title}</strong><small>${doctor} · ${time}</small></div>${badge(status,kind)}</div>`}
function stat(label,value,caption,icon){return `<article class="stat-card"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-caption">${caption}</div></article>`}
function showModal(title,body){document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-body').innerHTML=body;modal.hidden=false;document.querySelector('#modal-done').focus()}
function dashboard(){return `${header('Welcome to HealthSync','Manage your healthcare journey in one place.')}
  <div class="grid stats">${stat('Upcoming Appointments','02','Next visit tomorrow','▣')}${stat('Medical Records','08','Sample records on file','▤')}${stat('Prescriptions','03','1 active prescription','＋')}${stat('Notifications','04','2 unread updates','◉')}</div>
  <div class="section-heading"><div><h2>Quick actions</h2><p>Get to the things you need most.</p></div></div><div class="grid quick-grid">
  <button class="quick-card" data-view="appointments"><span class="quick-icon">＋</span><span><strong>Book Appointment</strong><small>Schedule a care visit</small></span></button><button class="quick-card" data-view="records"><span class="quick-icon">▤</span><span><strong>View Medical Records</strong><small>Review sample records</small></span></button><button class="quick-card" data-view="prescriptions"><span class="quick-icon">♧</span><span><strong>View Prescriptions</strong><small>Check medicine details</small></span></button><button class="quick-card" data-view="emergency"><span class="quick-icon">✚</span><span><strong>Emergency Assistance</strong><small>Demo request flow</small></span></button></div>
  <div class="grid dashboard-grid"><section class="panel">${panelHead('Upcoming appointments','<button class="text-link" data-view="appointments">View all →</button>')}${appointmentRow('08','OCT','General Consultation','Dr. Sarah Johnson','Today, 10:30 AM','Confirmed','green')}${appointmentRow('09','OCT','Follow-up Consultation','Dr. Arun Kumar','Tomorrow, 2:00 PM','Scheduled','blue')}<div class="info-banner">These appointments are fictional examples for the HealthSync demo.</div></section>
  <section class="panel">${panelHead('Recent medical activity')}<div class="activity"><span class="activity-icon">▤</span><div><strong>Medical record updated</strong><small>General consultation · Oct 06</small></div></div><div class="activity"><span class="activity-icon">＋</span><div><strong>Prescription issued</strong><small>Amoxicillin · Oct 04</small></div></div><div class="activity"><span class="activity-icon">✓</span><div><strong>Appointment completed</strong><small>Follow-up visit · Oct 02</small></div></div></section></div>`}
function appointments(){return `${header('Appointments','Review upcoming visits or explore the sample appointment history.')}<div class="info-banner"><strong>Sample data:</strong> Appointment details below are fictional and are not connected to a patient account.</div><section class="panel">${panelHead('Upcoming appointments','<button class="button primary" data-modal="Book appointment">＋ Book Appointment</button>')}<div class="table-wrap"><table><thead><tr><th>Appointment</th><th>Provider</th><th>Date & time</th><th>Type</th><th>Status</th><th></th></tr></thead><tbody><tr><td><strong>General Consultation</strong></td><td>Dr. Sarah Johnson</td><td>Oct 08, 2026 · 10:30 AM</td><td>In person</td><td>${badge('Confirmed')}</td><td><button class="text-link" data-modal="Appointment details">View</button></td></tr><tr><td><strong>Follow-up Consultation</strong></td><td>Dr. Arun Kumar</td><td>Oct 09, 2026 · 2:00 PM</td><td>Online</td><td>${badge('Scheduled','blue')}</td><td><button class="text-link" data-modal="Appointment details">View</button></td></tr></tbody></table></div></section><section class="panel">${panelHead('Previous appointments')}<div class="table-wrap"><table><thead><tr><th>Appointment</th><th>Provider</th><th>Date</th><th>Status</th></tr></thead><tbody><tr><td><strong>Follow-up Consultation</strong></td><td>Dr. Sarah Johnson</td><td>Oct 02, 2026</td><td>${badge('Completed')}</td></tr><tr><td><strong>General Consultation</strong></td><td>Dr. Arun Kumar</td><td>Sep 18, 2026</td><td>${badge('Completed')}</td></tr></tbody></table></div></section>`}
function records(){return `${header('Medical Records','A sample overview of patient information and clinical history.')}<div class="info-banner"><strong>Fictional patient:</strong> Jordan Davis · Patient ID HS-DEMO-1042. This page contains sample information only.</div><section class="panel"><div class="record-card" style="border:0;padding:0 0 16px"><div class="record-main"><span class="avatar">JD</span><div><h3>Jordan Davis</h3><p>Demo patient · Sample profile · Date of birth: Jan 14, 1990</p></div></div><span class="demo-pill">SAMPLE PROFILE</span></div></section><div class="section-heading"><div><h2>Recent records</h2><p>Example medical history entries</p></div></div><div class="cards-list">${[['General consultation','Seasonal allergies','Dr. Sarah Johnson','Oct 06, 2026'],['Follow-up visit','Routine follow-up','Dr. Arun Kumar','Sep 21, 2026'],['Annual check-up','Preventive care review','Dr. Sarah Johnson','Aug 12, 2026']].map(r=>`<article class="record-card"><div class="record-main"><span class="medicine-icon">▤</span><div><h3>${r[0]}</h3><p>Diagnosis: ${r[1]}<br>Doctor: ${r[2]} · Date: ${r[3]}</p></div></div><button class="button secondary small" data-modal="Medical record">View record</button></article>`).join('')}</div>`}
function prescriptions(){return `${header('Prescriptions','Review sample medication instructions and status.')}<div class="info-banner"><strong>Demo only:</strong> Medicine and dosage details below are fictional and are not medical advice.</div><div class="cards-list">${[['Amoxicillin','500 mg','Twice daily · 7 days','Dr. Sarah Johnson','Active'],['Vitamin D3','1000 IU','Once daily · 30 days','Dr. Arun Kumar','Active'],['Cetirizine','10 mg','Once daily · 5 days','Dr. Sarah Johnson','Completed']].map((r,i)=>`<article class="record-card"><div class="record-main"><span class="medicine-icon">♧</span><div><h3>${r[0]} <span style="font-weight:400;color:#74858b">${r[1]}</span></h3><p>${r[2]}<br>Prescribed by ${r[3]}</p></div></div>${badge(r[4],i===2?'blue':'green')}<button class="button secondary small" data-modal="Prescription details">View</button></article>`).join('')}</div>`}
function payments(){return `${header('Payments','View example invoices and payment statuses.')}<div class="info-banner"><strong>Sample billing data:</strong> No real charges or payments are made from this demonstration.</div><section class="panel">${panelHead('Invoices')}<div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Service</th><th>Amount</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody><tr><td><strong>INV-DEMO-2048</strong></td><td>General Consultation</td><td class="payment-total">$85.00</td><td>Oct 06, 2026</td><td>${badge('Paid')}</td><td><button class="text-link" data-modal="Invoice details">View</button></td></tr><tr><td><strong>INV-DEMO-2049</strong></td><td>Laboratory Services</td><td class="payment-total">$42.50</td><td>Oct 07, 2026</td><td>${badge('Pending','amber')}</td><td><button class="button secondary small" data-modal="Demo payment">Pay</button></td></tr><tr><td><strong>INV-DEMO-2042</strong></td><td>Follow-up Consultation</td><td class="payment-total">$55.00</td><td>Sep 21, 2026</td><td>${badge('Paid')}</td><td><button class="text-link" data-modal="Invoice details">View</button></td></tr></tbody></table></div></section>`}
function notifications(){return `${header('Notifications','Stay up to date with your care and HealthSync activity.')}<section class="panel">${panelHead('Recent notifications')}<div class="notice"><span class="activity-icon">▣</span><p><strong>Appointment reminder</strong><br>Your sample consultation with Dr. Sarah Johnson is scheduled for today at 10:30 AM.<small>Today · 8:00 AM · Demo notification</small></p></div><div class="notice"><span class="activity-icon">＋</span><p><strong>Prescription notification</strong><br>A sample prescription was added to your demo profile.<small>Oct 04, 2026 · Demo notification</small></p></div><div class="notice"><span class="activity-icon">◉</span><p><strong>Welcome to HealthSync</strong><br>This workspace uses fictional sample data for demonstration purposes.<small>Oct 01, 2026 · System notification</small></p></div></section>`}
function emergency(){return `${header('Emergency Assistance','This demonstration does not contact emergency services or healthcare providers.')}<section class="emergency-hero"><div><div class="emergency-symbol">✚</div><h2>Emergency Assistance</h2><p>Use this section to explore the HealthSync emergency request interface.</p><div class="warning-note">Demo behavior only · For a real emergency, contact your local emergency services.</div></div><button class="button danger" data-modal="Emergency demo request">Request Emergency Assistance</button></section><section class="panel" style="margin-top:18px">${panelHead('How the demo works')}<p style="font-size:11px;color:#74858b;line-height:1.7;margin:0">The request button displays an informational confirmation only. It does not create a real emergency case, send a notification, or dispatch medical assistance.</p></section>`}
function reports(){return `${header('Reports','Explore the reporting areas available in the HealthSync desktop application.')}<div class="info-banner">These report cards are examples; no live database report is being generated in this browser demo.</div><div class="grid report-grid">${[['▣','Appointment Report','Review appointment volume, status, and care schedules.'],['▤','Medical Record Summary','Summarize clinical record activity and visit history.'],['＄','Billing Summary','Review invoice totals and payment status.'],['◉','Patient Activity','See a timeline of patient care interactions.']].map(r=>`<article class="panel report-card"><span class="stat-icon">${r[0]}</span><h3>${r[1]}</h3><p>${r[2]}</p><button class="button secondary small" data-modal="${r[1]}">Open report</button></article>`).join('')}</div>`}
function patternsPage(){return `${header('Design Patterns','Explore the 23 GoF patterns implemented across the HealthSync project.')}<div class="info-banner">Each demonstration calls the existing Java <code>POST /execute</code> endpoint. It does not duplicate pattern logic.</div><div class="pattern-groups">${['Creational','Structural','Behavioral'].map(cat=>{let list=patterns.filter(p=>p[1]===cat);return `<section><div class="category-title"><h2>${cat} patterns</h2><span>${list.length} patterns</span></div><div class="grid pattern-grid">${list.map(([name,category,purpose],i)=>`<article class="pattern-card"><div class="pattern-top"><span class="pattern-number">PATTERN ${String(patterns.indexOf(list[i])+1).padStart(2,'0')}</span><span class="category-tag">${category}</span></div><h3>${name}</h3><p>${purpose}</p><button class="button secondary small run-pattern" data-pattern="${name}">Run Demo</button></article>`).join('')}</div></section>`}).join('')}</div>`}
const views={dashboard,appointments,records,prescriptions,payments,notifications,emergency,reports,patterns:patternsPage};
function render(view){if(!views[view])view='dashboard';content.innerHTML=views[view]();document.querySelector('#page-title').textContent=descriptions[view];document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#sidebar').classList.remove('open');document.querySelector('#scrim').classList.remove('show');window.scrollTo(0,0)}
document.querySelector('#navigation').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)render(b.dataset.view)});
content.addEventListener('click',async e=>{const view=e.target.closest('[data-view]');if(view){render(view.dataset.view);return}const demo=e.target.closest('[data-pattern]');if(demo){demo.disabled=true;demo.textContent='Running…';try{const response=await fetch('/execute',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({pattern:demo.dataset.pattern,input:'demo'})});const data=await response.json();showModal(`${demo.dataset.pattern} demonstration`,`<p>The existing HealthSync pattern class returned:</p><div class="modal-result"></div>`);document.querySelector('.modal-result').textContent=data.output||data.error||'No output returned.'}catch(err){showModal(`${demo.dataset.pattern} demonstration`,`<p>Could not reach the demo endpoint: ${err.message}</p>`)}finally{demo.disabled=false;demo.textContent='Run Demo'}return}const modalButton=e.target.closest('[data-modal]');if(modalButton){let message='This is a UI demonstration using sample data. No real patient, billing, or emergency action was performed.';if(modalButton.dataset.modal==='Emergency demo request')message='Demo only: no emergency request was sent and no assistance was dispatched. Contact your local emergency services for a real emergency.';showModal(modalButton.dataset.modal,`<p>${message}</p>`)}});
document.querySelector('#menu-toggle').addEventListener('click',()=>{document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#scrim').classList.toggle('show')});document.querySelector('#scrim').addEventListener('click',()=>{document.querySelector('#sidebar').classList.remove('open');document.querySelector('#scrim').classList.remove('show')});
document.querySelector('#modal-close').addEventListener('click',()=>modal.hidden=true);document.querySelector('#modal-done').addEventListener('click',()=>modal.hidden=true);modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.hidden=true});document.querySelector('#logout').addEventListener('click',()=>showModal('Demo workspace','<p>This sample dashboard does not have account authentication. No session was active.</p>'));
render('dashboard');
